version: '3.8'

volumes:
  postgres_data: 
  static_value:
  media_value:

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    hostname: 
      db
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    # image: tastybaev/foodgram-project-backend:latest
    restart: always
    volumes:
      - static_value:/code/static_backend/
      - media_value:/code/media/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    # image: tastybaev/foodgram-project-frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.6
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    restart: always
    depends_on:
      - backend
