# Generated by Django 3.2.7 on 2022-05-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=99, verbose_name='Хекскод цвета'),
        ),
    ]
