# Generated by Django 3.2.7 on 2022-06-04 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220517_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ShoppingList', to=settings.AUTH_USER_MODEL, verbose_name='Подписчик на корзину'),
        ),
    ]
